export const DUMMY_TASK = [
    {
        title: 'Create a wire frame1',
        startTime: '11:30',
        endTime: '12:00',
        id: '1',
        completed: false,
    },
    {
        title: 'Create a wire frame2',
        startTime: '11:30',
        endTime: '12:00',
        id: '2',
        completed: false,
    },
    {
        title: 'Create a wire frame3',
        startTime: '11:30',
        endTime: '12:00',
        id: '3',
        completed: false,
    },
    {
        title: 'Create a wire frame4',
        startTime: '11:30',
        endTime: '12:00',
        id: '4',
        completed: false,
    },
    {
        title: 'Create a wire frame5',
        startTime: '11:30',
        endTime: '12:00',
        id: '4',
        completed: false,
    },
    {
        title: 'Create a wire frame6',
        startTime: '11:30',
        endTime: '12:00',
        id: '4',
        completed: false,
    },
    {
        title: 'Create a wire frame7',
        startTime: '11:30',
        endTime: '12:00',
        id: '4',
        completed: false,
    },
    {
        title: 'Create a wire frame8',
        startTime: '11:30',
        endTime: '12:00',
        id: '4',
        completed: false,
    },
    {
        title: 'Create a wire frame9',
        startTime: '11:30',
        endTime: '12:00',
        id: '4',
        completed: false,
    },
    {
        title: 'Create a wire frame10',
        startTime: '11:30',
        endTime: '12:00',
        id: '4',
        completed: false,
    },
    {
        title: 'Create a wire frame11',
        startTime: '11:30',
        endTime: '12:00',
        id: '4',
        completed: false,
    },
    {
        title: 'Create a wire frame12',
        startTime: '11:30',
        endTime: '12:00',
        id: '4',
        completed: false,
    },
    {
        title: 'Create a wire frame13',
        startTime: '11:30',
        endTime: '12:00',
        id: '4',
        completed: false,
    },
    {
        title: 'Create a wire frame14',
        startTime: '11:30',
        endTime: '12:00',
        id: '4',
        completed: false,
    },
    {
        title: 'Create a wire frame15',
        startTime: '11:30',
        endTime: '12:00',
        id: '4',
        completed: false,
    },
    {
        title: 'Create a wire frame16',
        startTime: '11:30',
        endTime: '12:00',
        id: '4',
        completed: false,
    },
    {
        title: 'Create a wire frame17',
        startTime: '11:30',
        endTime: '12:00',
        id: '4',
        completed: false,
    },
    {
        title: 'Create a wire frame18',
        startTime: '11:30',
        endTime: '12:00',
        id: '4',
        completed: false,
    },
    {
        title: 'Create a wire frame19',
        startTime: '11:30',
        endTime: '12:00',
        id: '4',
        completed: false,
    },
    {
        title: 'Create a wire frame20',
        startTime: '11:30',
        endTime: '12:00',
        id: '4',
        completed: false,
    },
    {
        title: 'Create a wire frame21',
        startTime: '11:30',
        endTime: '12:00',
        id: '4',
        completed: false,
    },
    {
        title: 'Create a wire frame22',
        startTime: '11:30',
        endTime: '12:00',
        id: '4',
        completed: false,
    },
    {
        title: 'Create a wire frame23',
        startTime: '11:30',
        endTime: '12:00',
        id: '4',
        completed: false,
    },
    {
        title: 'Create a wire frame24',
        startTime: '11:30',
        endTime: '12:00',
        id: '4',
        completed: false,
    },
    {
        title: 'Create a wire frame25',
        startTime: '11:30',
        endTime: '12:00',
        id: '4',
        completed: false,
    },
    {
        title: 'Create a wire frame26',
        startTime: '11:30',
        endTime: '12:00',
        id: '4',
        completed: false,
    },
    {
        title: 'Create a wire frame27',
        startTime: '11:30',
        endTime: '12:00',
        id: '4',
        completed: false,
    },
    {
        title: 'Create a wire frame28',
        startTime: '11:30',
        endTime: '12:00',
        id: '4',
        completed: false,
    },
    {
        title: 'Create a wire frame29',
        startTime: '11:30',
        endTime: '12:00',
        id: '4',
        completed: false,
    },
    {
        title: 'Create a wire frame30',
        startTime: '11:30',
        endTime: '12:00',
        id: '4',
        completed: false,
    },
    {
        title: 'Create a wire frame31',
        startTime: '11:30',
        endTime: '12:00',
        id: '4',
        completed: false,
    },
    {
        title: 'Create a wire frame32',
        startTime: '11:30',
        endTime: '12:00',
        id: '4',
        completed: false,
    },
    
]